zeebe:
  client:
    broker:
      contactPoint: "zeebe:26500"
    security:
      plaintext: true
server:
  port: 9700

spring:
  cloud:
    stream:
      bindings:
        variablesInput:
          group: zeebe-app
          destination: alfamobile.zeebe.variables
          contentType: "application/json"
      kafka:
        binder:
          brokers: "http://kafka:9092"
